meta_product_name: "LeScreen"
meta_title: "recruitment made easy"
meta_description: "Speed up your recruitment with LeScreen's on-demand video interview plarform"
meta_image: "logometa.png" # should exist in `app/assets/images/`
